### PR TITLE
Fix "Up since ..." in the dashboard view page

### LINKED ISSUE #62: "Up since ..." not showing
### Description - What happened? *

- On the dashboard "Up since ..." does not show when hovering over the "Up" status.
Also I think we should place this hint more visibly in general, as it is not intuitive to hover over the UP status.

- The Dashboard displays the uptime of all components in percent. It is not apperant over which timespan this percentage is calculated. To my knowledge the calculation takes the last 30 days into account. Could you please add this information to the Dashboard?

- The Data Catalogue in the Dashboard is reffered to as "Broker". Could you please rename this to "Data Catalogue"?

### Expected Behavior *

/

### Observed Behavior *

/

### Steps to Reproduce

_No response_

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by illfixit**
_What issues does this PR close?_

closes #62 Up since ..." not showing

image

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [x] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts [hunk 1]
```diff
@@ -43,19 +43,24 @@ export class DashboardComponentUptimeCardComponent {
...
   }
   chartData: DonutChartData | null = null;
-  upSinceTooltip: string | null = null;
+  upSinceHumanized: string | null = null;
+
+  humanizeDuration(seconds: number | undefined | null): string {
+    if (seconds !== undefined && seconds !== null) {
+      return humanizeDuration(seconds);
+    }
+    return 'time period';
```
Comment (richardtreier) [inline authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts:62]: why this default?

File: authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/ComponentStatusApiServiceTest.kt [hunk 2]
```diff
@@ -107,28 +107,28 @@ class ComponentStatusApiServiceTest {
...
-        assertThat(resultEnv1.brokerStatus.timeSpan).isEqualTo(Duration.ofDays(30))
-        assertThat(resultEnv1.brokerStatus.upSince).isCloseTo(Duration.ofDays(5), Duration.ofSeconds(5))
+        assertThat(resultEnv1.brokerStatus.timeSpanSeconds).isEqualTo(2592000)
+        assertThat(resultEnv1.brokerStatus.upSinceSeconds).isCloseTo(432000, Offset.offset(5))
         assertThat(resultEnv1.dapsStatus.componentStatus).isEqualTo(ComponentOnlineStatus.MAINTENANCE.toDto())
         assertThat(resultEnv1.dapsStatus.uptimePercentage).isCloseTo(50.00, Offset.offset(0.1))
-        assertThat(resultEnv1.dapsStatus.timeSpan).isEqualTo(Duration.ofDays(30))
-        assertThat(resultEnv1.dapsStatus.upSince).isEqualTo(Duration.ZERO)
+        assertThat(resultEnv1.dapsStatus.timeSpanSeconds).isEqualTo(2592000)
+        assertThat(resultEnv1.dapsStatus.upSinceSeconds).isEqualTo(0)
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/ComponentStatusApiServiceTest.kt:115]: nit: as above

File: authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/ComponentStatusApiServiceTest.kt [hunk 3]
```diff
@@ -107,28 +107,28 @@ class ComponentStatusApiServiceTest {
...
         assertThat(resultEnv1.onlineConnectors).isEqualTo(2)
         assertThat(resultEnv1.disturbedConnectors).isEqualTo(3)
         assertThat(resultEnv1.offlineConnectors).isEqualTo(2)
 
         assertThat(resultEnv2.brokerStatus.componentStatus).isEqualTo(ComponentOnlineStatus.UP.toDto())
         assertThat(resultEnv2.brokerStatus.uptimePercentage).isEqualTo(100.00)
-        assertThat(resultEnv2.brokerStatus.timeSpan).isEqualTo(Duration.ofDays(30))
-        assertThat(resultEnv2.brokerStatus.upSince).isCloseTo(Duration.ofDays(31), Duration.ofSeconds(5))
+        assertThat(resultEnv2.brokerStatus.timeSpanSeconds).isEqualTo(2592000)
+        assertThat(resultEnv2.brokerStatus.upSinceSeconds).isCloseTo(2678400, Offset.offset(5))
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/ComponentStatusApiServiceTest.kt:127]: nit: as above

File: authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/ComponentStatusApiServiceTest.kt [hunk 4]
```diff
@@ -107,28 +107,28 @@ class ComponentStatusApiServiceTest {
...
         assertThat(resultEnv2.dapsStatus.componentStatus).isEqualTo(ComponentOnlineStatus.DOWN.toDto())
         assertThat(resultEnv2.dapsStatus.uptimePercentage).isEqualTo(0.00)
-        assertThat(resultEnv2.dapsStatus.timeSpan).isEqualTo(Duration.ofDays(30))
-        assertThat(resultEnv2.dapsStatus.upSince).isEqualTo(Duration.ZERO)
+        assertThat(resultEnv2.dapsStatus.timeSpanSeconds).isEqualTo(2592000)
+        assertThat(resultEnv2.dapsStatus.upSinceSeconds).isEqualTo(0)
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/test/kotlin/de/sovity/authorityportal/web/integration/pages/ComponentStatusApiServiceTest.kt:131]: nit: as above

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts [hunk 5]
```diff
@@ -43,19 +43,24 @@ export class DashboardComponentUptimeCardComponent {
     this.chartData = value
       .mapNotNull((it) => this.buildDonutChartData(it))
       .orElse(null);
-    this.upSinceTooltip = value
+    this.upSinceHumanized = value
       .mapNotNull((it) =>
```
Comment (richardtreier) [inline authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts:47]:
````ts
.mapNotNull(it => it.upSinceSeconds)
.mapNotNull(humanizeDuration)
.orElse(null);
```

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts (hunk 1 above)
Comment (richardtreier) [reply authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts:62]: Do you even need this custom wrapper?

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts [hunk 6]
```diff
@@ -43,19 +43,24 @@ export class DashboardComponentUptimeCardComponent {
...
   }
   get data(): Fetched<UptimeStatusDto | undefined> {
     return this._data;
   }
   chartData: DonutChartData | null = null;
-  upSinceTooltip: string | null = null;
+  upSinceHumanized: string | null = null;
+
+  humanizeDuration(seconds: number | undefined | null): string {
+    if (seconds !== undefined && seconds !== null) {
```
Comment (richardtreier) [inline authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts:59]: same as if (seconds != null)

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts (hunk 1 above)
Comment (kamilczaja) [inline authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts:62]: Is this `if` necessary here? If I see this correctly, you're checking `upSinceSeconds` for `null` in `line 48`.
Also, why are you returning 'time period' here? Is this a placeholder?

Comment: Also, this function naming really confused me. I needed a minute to figure out that this is indeed not a recursive call...

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.html [hunk 7]
```diff
@@ -41,8 +35,11 @@ <h3 class="font-semibold text-sm">
     <div class="truncate text-sm font-medium text-gray-500 whitespace-normal">
       Uptime
     </div>
-    <div class="mt-1 text-3xl tracking-tight text-gray-900">
+    <div class="my-1 text-3xl tracking-tight text-gray-900">
       {{ data.data.uptimePercentage / 100 | percent }}
     </div>
+    <div class="text-sm text-gray-500">
+      of the last {{ humanizeDuration(data.data.timeSpanSeconds) }}
```
Comment (kamilczaja) [inline authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.html:42]: "in the last ..." sounds better imo

File: CHANGELOG.md [hunk 8]
```diff
@@ -19,6 +19,7 @@ please see [changelog_updates.md](docs/dev/changelog_updates.md).
 - Fixed connectors not showing on operator's "All connectors" list ([#119](https://github.com/sovity/authority-portal/issues/119))
 - Changed Access Token Lifespan to be one minute ([#111](https://github.com/sovity/authority-portal/issues/111))
 - Fixed an issue with connector URLs not being validated correctly in the UI ([#115](https://github.com/sovity/authority-portal/issues/115))
+- Fixed "Up since ..." in the dashboard view page ([#62](https://github.com/sovity/authority-portal/issues/62))
```
Comment (kamilczaja) [inline CHANGELOG.md:22]: Fix wording here: "on the dashboard page"

Or adjust the wording completely to something along the lines of "Dashboard: Changed the component uptime duration to be shown next to the status instead of showing it in a tooltip"

**Review by kamilczaja — CHANGES_REQUESTED** [review]

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.html (hunk 7 above)
Comment (illfixit) [reply authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.html]: done

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts (hunk 1 above)
Comment (illfixit) [reply authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts]: implemented in html instead

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts (hunk 5 above)
Comment (illfixit) [reply authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts]: done

File: authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts (hunk 1 above)
Comment (illfixit) [reply authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts]: makes sense, changed the name of the function. the reason is the "hacky" import in angular of functions from another component

Comment (illfixit) [reply authority-portal-frontend/src/app/pages/dashboard-page/dashboard-component-uptime-card/dashboard-component-uptime-card.component.ts]: makes sense, changed the name of the function. the reason is the "hacky" import in angular of functions from another component

**Review by kamilczaja — APPROVED** [review]
LGTM
