### PR TITLE
Fix user de-/reactivation

### LINKED ISSUE #82: No connection between status of org and user
### Description - What happened? *

It seems like the status of an organization has no impact on its users.

### Expected Behavior *

/

### Observed Behavior *

/

### Steps to Reproduce

_No response_

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

rejected_org

### PR DESCRIPTION
**Pull request by jridderbusch**
closes #82 

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [x] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt [hunk 1]
```diff
@@ -172,6 +172,7 @@ class UiResourceImpl : UiResource {
     @Transactional
     override fun deactivateParticipantUser(userId: String): IdResponse {
         authUtils.requiresRole(Roles.UserRoles.PARTICIPANT_ADMIN)
+        authUtils.requiresRegistrationStatus(userId, UserRegistrationStatus.ACTIVE)
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt:175]: Does it make sense to restrict this to `ACTIVE`? What if I want to deactivate a user that has been invited by someone?

Also, not clear who the function refers to, maybe name it `requiresTargetRegistrationStatus` to be more consistent?

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt [hunk 2]
```diff
@@ -180,6 +181,7 @@ class UiResourceImpl : UiResource {
     @Transactional
     override fun reactivateParticipantUser(userId: String): IdResponse {
         authUtils.requiresRole(Roles.UserRoles.PARTICIPANT_ADMIN)
+        authUtils.requiresRegistrationStatus(userId, UserRegistrationStatus.DEACTIVATED)
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt:184]: Not clear who the function refers to, maybe name it `requiresTargetRegistrationStatus` to be more consistent?

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt [hunk 3]
```diff
@@ -210,13 +212,15 @@ class UiResourceImpl : UiResource {
     @Transactional
     override fun deactivateAnyUser(userId: String): IdResponse {
         authUtils.requiresRole(Roles.UserRoles.AUTHORITY_ADMIN)
+        authUtils.requiresRegistrationStatus(userId, UserRegistrationStatus.ACTIVE)
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt:215]: Same as above

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt [hunk 4]
```diff
@@ -210,13 +212,15 @@ class UiResourceImpl : UiResource {
...
         authUtils.requiresTargetNotSelf(userId)
         return userDeactivationApiService.deactivateUser(userId, loggedInUser.userId)
     }
 
     @Transactional
     override fun reactivateAnyUser(userId: String): IdResponse {
         authUtils.requiresRole(Roles.UserRoles.AUTHORITY_ADMIN)
+        authUtils.requiresRegistrationStatus(userId, UserRegistrationStatus.DEACTIVATED)
```
Comment (kamilczaja) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt:223]: Same as above

**Review by kamilczaja — CHANGES_REQUESTED** [review]

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt (hunk 1 above)
Comment (jridderbusch) [reply authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt]: This makes sense, because otherwise INVITED/PENDING users can be deactivated and then activated, leading to an inconsistens state.

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt (hunk 3 above)
Comment (jridderbusch) [reply authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/UiResourceImpl.kt]: See above

**Review by kamilczaja — APPROVED** [review]
LGTM
