### PR TITLE
Fix CaaS not showing up in provided connectors and provider ID not displaying

### LINKED ISSUE #206: MDS-ID missing on provider of CaaS
### Description - What happened? *

The Connector Details page provides information about the hosting company. This field consists of (1) the hosting companies name and (2) the hosting companies MDS-ID. This is displayed correctly for premium CaaS but with basic CaaS orderd through the portal the MDS-ID is missing.

### Expected Behavior *

Provider should be shown in a nice format.
@kamilczaja: The MDS-ID is not known for sovity on premium CaaS because they can be requested even before sovity is registered in the portal and assigned an MDS-ID. A possible solution is to fix the formatting by removing the trailing comma

### Observed Behavior *

MDS-ID is missing, company name has a trailing comma

### Steps to Reproduce

- Request a free CaaS through the MDS Portal.
- Navigate to "My Connectors" or "All Connectors".
- Klick on the newly requested Connector to open the Connector Details Page.
- The field "Hosted by" says "sovity GmbH, ".
- Expected behaviour: The field "Hosted by" should state the organization name as well as the MDS-ID.

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kamilczaja**
_What issues does this PR close?_
Closes #206 

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+            .toSet()
+
+        if (connectors.isNotEmpty()) {
+            val orgId = organizationService.getOrganizationIdByName("sovity GmbH")
+
+            connectors.forEach {
+                it.providerOrganizationId = orgId
+            }
+            dsl.batchUpdate(connectors).execute()
+        }
```
Comment (kulgg) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt:43]: nit; could be inverted aka connectors.isEmpyt() early return and so on

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import org.jooq.DSLContext
+
+@ApplicationScoped
+class CaasProviderIdUpdateService(
+    val dsl: DSLContext,
+    val organizationService: OrganizationService
+) {
+
+    @Scheduled(every = "24h")
+    fun updateMissingProviderIds() {
```
Comment (kulgg) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt:29]: so does this really have to be done every 24h or do new connectors now automatically get the providerId set and we would only need this executed once?

**Review by kulgg — CHANGES_REQUESTED** [review]

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt (hunk 2 above)
Comment (kamilczaja) [reply authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasProviderIdUpdateService.kt:29]: New connectors get the providerId set only if sovity is already registered, as soon as sovity registers, this could be executed only once (by firing an event or so I guess).
But consider this:

- Delete the organization sovity
- Request a CaaS
- Re-invite sovity much later

Then the connector would forever lack the providerId. It's a very stupid edge-case but the implemented method would prevent it

**Review by kulgg — APPROVED** [review]
LGTM
