### PR TITLE
Data Offer CSV Export LIVE -> Available

### LINKED ISSUE #283: CSV-Export: Available vs LIVE
### Description - What happened? *

Original Title: `Available datasource type not visible in data offers csv report`

`Instead of Available datasource type added as LIVE datasource type in the data offer csv report.`
-> In the AP, a data-source type is called “Available” in the UI, in the CSV export it is called “LIVE”, which is inconsistent.

### Expected Behavior *

`Available datasource type should be added in data offer csv report.`

### Observed Behavior *

`LIVE` instead of `Available` in CSV Export

### Steps to Reproduce

```
Steps to reproduce the behavior:
- Log in to the MDS Portal.
- Navigate to "Dashboard page"
- Click and download data offer CSV report
```

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### LINKED ISSUE #292: CaaS Update Service runs with CaaS client disabled
### Description - What happened? *

The Scheduled update calls to the CP should be disabled if the sovity OIDC client is set to `disabled`.
Otherwise, failing authentication calls to the CP Keycloak will flood our logs regularly

### Expected Behavior *

.

### Observed Behavior *

.

### Steps to Reproduce

_No response_

### Context Information

_No response_

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kamilczaja**
_What issues does this PR close?_
Closes #283 
Closes #292

Includes a small non-user-facing bugfix

```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [x] I have performed a **self-review**
```

### CODE REVIEW

File: authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasUpdateService.kt [hunk 1]
```diff
@@ -31,16 +32,19 @@ class CaasUpdateService(
     val connectorService: ConnectorService,
     val caasClient: CaasClient,
     val dapsClientService: DapsClientService,
+    @ConfigProperty(name = "quarkus.oidc-client.sovity.client-enabled") val isCaasClientEnabled: Boolean
```
Comment (Linkshegelianer) [inline authority-portal-backend/authority-portal-quarkus/src/main/kotlin/de/sovity/authorityportal/web/services/CaasUpdateService.kt:35]: Tbh this violates Kotlin [coding convention about annotations](https://kotlinlang.org/docs/coding-conventions.html#annotations). I'm not going to die on this hill, but I would use the common injection here

**Review by Linkshegelianer — CHANGES_REQUESTED** [review]

**Review by Linkshegelianer — APPROVED** [review]
LGBT
